import { chromium } from 'playwright'
const dir = process.argv[2] ?? './smoke-shots'
import { mkdirSync } from 'node:fs'
mkdirSync(dir, { recursive: true })
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1200, height: 900 } })
const errs = []
p.on('console', m => m.type() === 'error' && errs.push(m.text()))
p.on('pageerror', e => errs.push(String(e)))
await p.goto('http://localhost:4319/')
await p.waitForTimeout(1500)
await p.screenshot({ path: `${dir}/1-tree.png` })
await p.getByRole('treeitem', { name: 'الأول' }).first().click()
await p.waitForTimeout(900)
await p.screenshot({ path: `${dir}/2-detail.png` })
const kids = await p.getByRole('heading', { name: /الأبناء/ }).textContent()
await p.getByRole('button', { name: 'الثاني' }).click()
await p.waitForTimeout(500)
await p.screenshot({ path: `${dir}/3-nav.png` })
await p.getByRole('button', { name: 'إضافة ابن', exact: true }).click()
await p.waitForTimeout(500)
await p.getByLabel('الاسم').fill('التاسع')
await p.getByRole('button', { name: 'حفظ' }).click()
await p.waitForTimeout(1200)
await p.screenshot({ path: `${dir}/4-added.png` })
await p.keyboard.press('Escape')
await p.waitForTimeout(400)
await p.reload()
await p.waitForTimeout(1500)
await p.screenshot({ path: `${dir}/5-reload.png` })
const persisted = await p.getByRole('treeitem', { name: 'التاسع' }).count()
console.log(JSON.stringify({ kids, persisted, errs }, null, 1))
await b.close()
